version: 1.0.19

user:
  name: ç™½äº‘è‹ç‹—
  domain: https://www.imalun.com
  avatar: https://www.imalun.com/images/avatar.jpg
  title: ä¸€è§‰æ¸¸ä»™å¥½æ¢¦ï¼Œä»»å®ƒç«¹å†·æ¾å¯’ã€‚è½©è¾•äº‹ï¼Œå¤ä»Šè°ˆï¼Œé£æµæ²³å±±ã€‚æ²‰é†‰è´Ÿç™½é¦–ï¼Œèˆ’æ€€æˆå¤§è§‚ã€‚é†’ï¼Œäº¦åœ¨äººé—´ï¼›æ¢¦ï¼Œäº¦åœ¨äººé—´
  desc: é†’ï¼Œäº¦åœ¨äººé—´ï¼›æ¢¦ï¼Œäº¦åœ¨äººé—´ã€‚
  birthDay: 11/19/2019 17:00:00 #è®¡æ—¶å¼€å§‹æ—¶é—´

favicon:
  visibilitychange: true
  narmal: /images/favicon.png
  hidden: /images/failure.png
  show_text: (/â‰§â–½â‰¦/)å’¦ï¼åˆå¥½äº†ï¼
  hide_text: (â—â€”â—)å–”å“Ÿï¼Œå´©æºƒå•¦ï¼
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

post_wordcount:
  wordcount: true # å•ç¯‡ å­—æ•°ç»Ÿè®¡
  min2read: true # å•ç¯‡ é˜…è¯»æ—¶é•¿

# æ˜¯å¦å›ºå®šå¤´
fixed_header: false

# å¤´éƒ¨èœå•
menu:
  nav:
    - title: ğŸŒˆ&nbsp;ç™½äº‘è‹ç‹—
      url: /
    - title: ğŸ“¦&nbsp;å½’æ¡£
      url: /archives
    - title: ğŸ”—&nbsp;å‹æƒ…è¿æ¥
      url: /links
    - title: ğŸ“§&nbsp;ç•™è¨€
      url: /comment
    - title: ğŸ˜‰&nbsp;å…³äº
      url: /about
    - title: ğŸª&nbsp;è™«æ´
      url: //foreverblog.cn/go.html

# å¼€å¯ Service Worker
sw: true

# å¼€å¯æ–‡ç« ç›®å½•
is_toc: true

# rss åœ°å€
rss: atom.xml

#
canonical: true

# cdn åœ°å€
cdn:
  css: 
    - //at.alicdn.com/t/font_1518765_5jbj7btfht2.css
    - //cdn.jsdelivr.net/gh/fancyapps/fancybox/dist/jquery.fancybox.min.css
  js:
    - //cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js
    - //cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
    - //cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min.js
    - //at.alicdn.com/t/font_1518765_5jbj7btfht2.js
    - //imgcache.qq.com/qcloud/tcbjs/1.6.0/tcb.js
    - //cdn.jsdelivr.net/gh/fancyapps/fancybox/dist/jquery.fancybox.min.js

# å¤´åƒé…ç½®
avatar:
  gravatar: https://gravatar.loli.net/avatar/
  qq: https://q1.qlogo.cn/g?b=qq&s=100